"use client";

import { Check, Cloud, Copy, HardDrive, LogOut, MailPlus, ShieldCheck, Trash2, UserRound } from "lucide-react";
import { useState, type FormEvent } from "react";
import { toast } from "sonner";
import { useAuth } from "@/contexts/auth-context";
import { useTrip } from "@/contexts/trip-context";
import { emailSchema } from "@/lib/schemas";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog } from "@/components/ui/dialog";

export default function SettingsPage(){const{user,signOut}=useAuth();const{workspace,online,trustedDevice,firebaseMode,setTrustedDevice,updateTrip}=useTrip();const[inviteOpen,setInviteOpen]=useState(false);const[saving,setSaving]=useState(false);const trip=workspace.trip;const isOwner=user?.email===trip.ownerEmail;
  const saveTrip=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setSaving(true);const data=new FormData(event.currentTarget);try{await updateTrip({title:String(data.get("title")),subtitle:String(data.get("subtitle")),startDate:String(data.get("startDate")),endDate:String(data.get("endDate")),timezone:String(data.get("timezone"))});toast.success("旅程設定已更新")}catch(error){toast.error(error instanceof Error?error.message:"更新失敗")}finally{setSaving(false)}};
  const invite=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const value=new FormData(event.currentTarget).get("email");const parsed=emailSchema.safeParse(value);if(!parsed.success){toast.error(parsed.error.issues[0].message);return}if(trip.memberEmails?.includes(parsed.data)){toast.error("這個帳號已在旅伴名單中");return}try{await updateTrip({memberEmails:[...(trip.memberEmails??[]),parsed.data]});toast.success("旅伴已加入名單");setInviteOpen(false)}catch(error){toast.error(error instanceof Error?error.message:"邀請失敗")}};
  const remove=async(email:string)=>{if(email===trip.ownerEmail)return;if(!confirm(`確定移除 ${email}？`))return;try{await updateTrip({memberEmails:(trip.memberEmails??[]).filter((item)=>item!==email)});toast.success("已移除旅伴")}catch(error){toast.error(error instanceof Error?error.message:"移除失敗")}};
  const copyLink=async()=>{await navigator.clipboard.writeText(`${window.location.origin}/trip/${trip.id}/today`);toast.success("邀請連結已複製")};
  return <div className="page-wrap"><header className="page-header"><div><span className="eyebrow">TRIP SETTINGS</span><h1 className="page-title">旅程設定</h1><p className="page-description">管理旅程資訊、旅伴與這台裝置的離線資料。</p></div></header>
  <div className="grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><div className="space-y-6"><section className="card p-5 sm:p-7"><div className="mb-6 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-[#e1ece5] text-[#1f6a4a]"><Cloud size={19}/></div><div><h2 className="m-0 text-lg font-extrabold">基本資料</h2><p className="mt-1 mb-0 text-xs text-[#77817b]">所有旅伴都能更新</p></div></div><form className="grid-form" onSubmit={saveTrip}><label className="span-2"><span className="field-label">旅程名稱</span><input className="input" name="title" defaultValue={trip.title} required/></label><label className="span-2"><span className="field-label">副標題</span><input className="input" name="subtitle" defaultValue={trip.subtitle}/></label><label><span className="field-label">開始日期</span><input className="input" type="date" name="startDate" defaultValue={trip.startDate} required/></label><label><span className="field-label">結束日期</span><input className="input" type="date" name="endDate" defaultValue={trip.endDate} required/></label><label className="span-2"><span className="field-label">旅程時區</span><select className="select" name="timezone" defaultValue={trip.timezone??"Europe/Prague"}><option value="Europe/Prague">Europe/Prague（中歐）</option><option value="Asia/Taipei">Asia/Taipei（台北）</option></select></label><div className="span-2 flex justify-end"><Button type="submit" disabled={!online} loading={saving}>儲存設定</Button></div></form></section>
    <section className="card overflow-hidden"><div className="flex items-center justify-between gap-3 border-b border-[#e3e6e1] px-5 py-5 sm:px-7"><div><h2 className="m-0 text-lg font-extrabold">旅伴名單</h2><p className="mt-1 mb-0 text-xs text-[#77817b]">名單中的 Google 帳號可查看與編輯內容</p></div>{isOwner&&<Button size="sm" disabled={!online} onClick={()=>setInviteOpen(true)}><MailPlus size={15}/>加入旅伴</Button>}</div><div className="divide-y divide-[#e7e9e5]">{trip.memberEmails?.map((email)=><div key={email} className="flex items-center gap-3 px-5 py-4 sm:px-7"><div className="grid h-9 w-9 place-items-center rounded-full bg-[#edf0ec] text-[#65706a]"><UserRound size={17}/></div><div className="min-w-0 flex-1"><div className="truncate text-sm font-bold">{email}</div><div className="mt-1 flex gap-2">{email===trip.ownerEmail&&<Badge tone="green">擁有者</Badge>}{email===user?.email&&<Badge tone="neutral">你</Badge>}</div></div>{isOwner&&email!==trip.ownerEmail&&<Button variant="ghost" size="icon" disabled={!online} onClick={()=>void remove(email)} aria-label="移除旅伴"><Trash2 size={15}/></Button>}</div>)}</div>{isOwner&&<div className="flex items-center justify-between gap-3 bg-[#f7f8f5] px-5 py-4 sm:px-7"><span className="text-xs text-[#737d77]">加入名單後，將連結傳給旅伴</span><Button size="sm" variant="secondary" onClick={()=>void copyLink()}><Copy size={14}/>複製連結</Button></div>}</section></div>
    <aside className="space-y-6"><section className="card p-5 sm:p-6"><div className="mb-5 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-[#e7edf3] text-[#3e6681]"><HardDrive size={19}/></div><div><h2 className="m-0 text-lg font-extrabold">離線資料</h2><p className="mt-1 mb-0 text-xs text-[#77817b]">僅限受信任的私人裝置</p></div></div><div className="rounded-2xl bg-[#f2f4f1] p-4"><div className="flex items-center justify-between gap-3"><div><div className="text-sm font-extrabold">受信任裝置</div><div className="mt-1 text-xs leading-5 text-[#747e78]">啟用後，曾查看的行程會保存在這台裝置。</div></div><button role="switch" aria-checked={trustedDevice} onClick={()=>setTrustedDevice(!trustedDevice)} className={`relative h-7 w-12 shrink-0 rounded-full transition ${trustedDevice?"bg-[#1f6a4a]":"bg-[#bfc5c1]"}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow transition ${trustedDevice?"left-6":"left-1"}`}/></button></div></div><p className="mt-4 mb-0 text-[11px] leading-5 text-[#818a85]">登出時會清除 Firestore 離線快取。離線期間只能查看，無法新增或修改資料。</p></section>
    <section className="card p-5 sm:p-6"><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-3"><ShieldCheck size={20} className="text-[#1f6a4a]"/><h2 className="m-0 text-base font-extrabold">連線狀態</h2></div><Badge tone={firebaseMode?"green":"amber"}>{firebaseMode?"Firebase":"展示模式"}</Badge></div><ul className="m-0 space-y-3 p-0 text-xs text-[#68736c]">{["Google 帳號驗證","旅伴名單權限","交易式衝突保護"].map((text)=><li key={text} className="flex items-center gap-2"><Check size={14} className="text-[#1f6a4a]"/>{text}</li>)}</ul></section><Button variant="secondary" className="w-full" onClick={()=>void signOut()}><LogOut size={16}/>登出並清除本機資料</Button></aside></div>
  <Dialog open={inviteOpen} onClose={()=>setInviteOpen(false)} title="加入旅伴" description="對方需使用相同 Email 的 Google 帳號登入" footer={<><Button variant="secondary" onClick={()=>setInviteOpen(false)}>取消</Button><Button form="invite-form" type="submit">加入名單</Button></>}><form id="invite-form" onSubmit={invite}><label><span className="field-label">Google 帳號 Email</span><input className="input" type="email" name="email" placeholder="travelmate@gmail.com" autoFocus required/></label></form></Dialog></div>}
