"use client";

import { BedDouble, BusFront, Edit3, ExternalLink, Plus, TicketCheck, Trash2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { useTrip } from "@/contexts/trip-context";
import { bookingStatusLabels, ticketStatusLabels, transportTypeLabels } from "@/lib/labels";
import { formatCurrency, formatUpdatedAt } from "@/lib/utils";
import type { Accommodation, Ticket, TransportBooking } from "@/types/types";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { EmptyState } from "@/components/ui/empty-state";
import { BookingEditor } from "@/components/booking-editor";

type Tab="accommodation"|"transport"|"ticket";type Item=Accommodation|TransportBooking|Ticket;
export default function BookingsPage(){const{workspace,online,upsertEntity,deleteEntity}=useTrip();const[tab,setTab]=useState<Tab>("accommodation");const[editing,setEditing]=useState<Item|null|undefined>(undefined);const items=tab==="accommodation"?workspace.accommodations:tab==="transport"?workspace.transportBookings:workspace.tickets;const collection=tab==="accommodation"?"accommodations":tab==="transport"?"transportBookings":"tickets";
  const remove=async(item:Item,label:string)=>{if(!confirm(`確定刪除「${label}」？相關行程中的引用需另外調整。`))return;try{await deleteEntity(collection,item);toast.success("預訂已刪除")}catch(error){toast.error(error instanceof Error?error.message:"刪除失敗")}};
  return <div className="page-wrap"><header className="page-header"><div><span className="eyebrow">RESERVATIONS</span><h1 className="page-title">預訂管理</h1><p className="page-description">住宿、城際交通與票券，出發前快速確認。</p></div><Button disabled={!online} onClick={()=>setEditing(null)}><Plus size={16}/>新增{tab==="accommodation"?"住宿":tab==="transport"?"交通":"票券"}</Button></header>
  <div className="mb-6 flex gap-2 border-b border-[#dfe2dd]"><TabButton active={tab==="accommodation"} onClick={()=>setTab("accommodation")} icon={BedDouble} label="住宿" count={workspace.accommodations.length}/><TabButton active={tab==="transport"} onClick={()=>setTab("transport")} icon={BusFront} label="交通" count={workspace.transportBookings.length}/><TabButton active={tab==="ticket"} onClick={()=>setTab("ticket")} icon={TicketCheck} label="票券" count={workspace.tickets.length}/></div>
  <div className="grid gap-4 lg:grid-cols-2">{items.map((raw)=>{const item=raw as Item;if(tab==="accommodation"){const hotel=item as Accommodation;return <BookingCard key={item.id} title={hotel.hotelName||`${hotel.city}住宿`} subtitle={`${hotel.checkIn} → ${hotel.checkOut} · ${hotel.nights} 晚`} status={bookingStatusLabels[hotel.status]} tone={hotel.status==="confirmed"||hotel.status==="booked"?"green":"amber"} meta={[hotel.bookingPlatform,hotel.bookingNumber&&`#${hotel.bookingNumber}`].filter(Boolean).join(" · ")} price={formatCurrency(hotel.price,hotel.currency)} link={hotel.bookingUrl} item={item} onEdit={()=>setEditing(item)} onDelete={()=>void remove(item,hotel.hotelName||hotel.city)}/>;}if(tab==="transport"){const ride=item as TransportBooking;return <BookingCard key={item.id} title={ride.title} subtitle={`${ride.date} · ${ride.from} → ${ride.to}`} status={bookingStatusLabels[ride.status]} tone={ride.status==="confirmed"||ride.status==="booked"?"green":"amber"} meta={[transportTypeLabels[ride.type],ride.provider,ride.serviceNumber].filter(Boolean).join(" · ")} price={formatCurrency(ride.price,ride.currency)} link={ride.ticketUrl} item={item} onEdit={()=>setEditing(item)} onDelete={()=>void remove(item,ride.title)}/>;}const ticket=item as Ticket;return <BookingCard key={item.id} title={ticket.name} subtitle={`${ticket.date}${ticket.time?` · ${ticket.time}`:""}`} status={ticketStatusLabels[ticket.status]} tone={ticket.status==="purchased"?"green":"amber"} meta={ticket.bookingNumber?`#${ticket.bookingNumber}`:""} price={formatCurrency(ticket.price,ticket.currency)} link={ticket.ticketUrl||ticket.fileUrl} item={item} onEdit={()=>setEditing(item)} onDelete={()=>void remove(item,ticket.name)}/>;})}</div>
  {items.length===0&&<EmptyState icon={TicketCheck} title="尚無預訂資料" description="新增住宿、交通或票券，集中保存重要資訊。" action={<Button onClick={()=>setEditing(null)}><Plus size={16}/>新增資料</Button>}/>}<BookingEditor open={editing!==undefined} kind={tab} item={editing} onClose={()=>setEditing(undefined)} onSave={async(item)=>upsertEntity(collection,{...item,sortOrder:item.sortOrder??items.length})}/></div>}

function TabButton({active,onClick,icon:Icon,label,count}:{active:boolean;onClick:()=>void;icon:typeof BedDouble;label:string;count:number}){return <button onClick={onClick} className={`flex items-center gap-2 border-b-2 px-3 py-3 text-sm font-bold ${active?"border-[#1f6a4a] text-[#1f6a4a]":"border-transparent text-[#747e78]"}`}><Icon size={17}/>{label}<span className={`rounded-full px-2 py-0.5 text-[10px] ${active?"bg-[#dfece4]":"bg-[#e7e9e6]"}`}>{count}</span></button>}
function BookingCard({title,subtitle,status,tone,meta,price,link,item,onEdit,onDelete}:{title:string;subtitle:string;status:string;tone:"green"|"amber";meta:string;price:string;link?:string;item:Item;onEdit:()=>void;onDelete:()=>void}){const{online}=useTrip();return <article className="card flex flex-col p-5"><div className="flex items-start justify-between gap-3"><Badge tone={tone}>{status}</Badge><div className="flex"><Button variant="ghost" size="icon" disabled={!online} onClick={onEdit} aria-label="編輯"><Edit3 size={15}/></Button><Button variant="ghost" size="icon" disabled={!online} onClick={onDelete} aria-label="刪除"><Trash2 size={15}/></Button></div></div><h2 className="mt-4 mb-1 text-lg font-black tracking-[-.02em]">{title}</h2><p className="m-0 text-sm text-[#67726c]">{subtitle}</p>{meta&&<p className="mt-3 mb-0 text-xs font-bold text-[#7b847f]">{meta}</p>}<div className="mt-auto flex items-end justify-between gap-3 pt-6"><div><div className="text-[10px] font-bold text-[#89918d]">費用</div><div className="mt-1 text-lg font-black">{price}</div><div className="mt-1 text-[10px] text-[#959c98]">{formatUpdatedAt(item.updatedAt)}{item.updatedBy&&` · ${item.updatedBy.name}`}</div></div>{link&&<a className="inline-flex h-10 items-center gap-2 rounded-xl border border-[#d7dbd7] bg-white px-3 text-xs font-bold text-[#1f6a4a]" href={link} target="_blank" rel="noreferrer">開啟連結<ExternalLink size={13}/></a>}</div></article>}
