"use client";

import { useState, type FormEvent } from "react";
import { toast } from "sonner";
import { Button } from "./ui/button";
import { Dialog } from "./ui/dialog";
import { createId } from "@/lib/utils";
import type { City, DayTransport, Place, TripDay, TransportType } from "@/types/types";

const field = (form: FormData, name: string) => String(form.get(name) ?? "").trim();
const optional = (value: string) => value || undefined;

interface BaseEditorProps<T> { open: boolean; item?: T | null; onClose: () => void; onSave: (item: T) => Promise<void>; }

export function CityEditor({ open, item, onClose, onSave }: BaseEditorProps<City>) {
  const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setSaving(true);
    const form = new FormData(event.currentTarget);
    try {
      await onSave({ id: item?.id ?? createId("city"), name: field(form,"name"), englishName: field(form,"englishName"), country: field(form,"country"), arrivalDate: field(form,"arrivalDate"), departureDate: field(form,"departureDate"), nights: Number(field(form,"nights")), accommodationId: optional(field(form,"accommodationId")), note: optional(field(form,"note")), sortOrder: item?.sortOrder, createdAt: item?.createdAt, updatedAt: item?.updatedAt, updatedBy: item?.updatedBy });
      toast.success(item ? "城市已更新" : "城市已新增"); onClose();
    } catch (error) { toast.error(error instanceof Error ? error.message : "儲存失敗"); } finally { setSaving(false); }
  };
  return <Dialog open={open} onClose={onClose} title={item ? "編輯城市" : "新增城市"} footer={<><Button variant="secondary" onClick={onClose}>取消</Button><Button type="submit" form="city-form" loading={saving}>儲存</Button></>}><form id="city-form" className="grid-form" onSubmit={submit}><Field label="中文名稱"><input className="input" name="name" defaultValue={item?.name} required /></Field><Field label="英文名稱"><input className="input" name="englishName" defaultValue={item?.englishName} required /></Field><Field label="國家"><input className="input" name="country" defaultValue={item?.country} required /></Field><Field label="晚數"><input className="input" type="number" min="0" name="nights" defaultValue={item?.nights ?? 1} required /></Field><Field label="抵達日期"><input className="input" type="date" name="arrivalDate" defaultValue={item?.arrivalDate} required /></Field><Field label="離開日期"><input className="input" type="date" name="departureDate" defaultValue={item?.departureDate} required /></Field><Field label="住宿 ID" className="span-2"><input className="input" name="accommodationId" defaultValue={item?.accommodationId} /></Field><Field label="備註" className="span-2"><textarea className="textarea" name="note" defaultValue={item?.note} /></Field></form></Dialog>;
}

export function DayEditor({ open, item, cities, onClose, onSave }: BaseEditorProps<TripDay> & { cities: City[] }) {
  const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); const form = new FormData(event.currentTarget); try { await onSave({ id: item?.id ?? createId("day"), dayNumber: Number(field(form,"dayNumber")), date: field(form,"date"), cityId: field(form,"cityId"), title: field(form,"title"), subtitle: optional(field(form,"subtitle")), note: optional(field(form,"note")), places: item?.places ?? [], transportation: item?.transportation ?? [], sortOrder: item?.sortOrder, createdAt: item?.createdAt, updatedAt: item?.updatedAt, updatedBy: item?.updatedBy }); toast.success(item ? "行程日已更新" : "行程日已新增"); onClose(); } catch (error) { toast.error(error instanceof Error ? error.message : "儲存失敗"); } finally { setSaving(false); } };
  return <Dialog open={open} onClose={onClose} title={item ? "編輯行程日" : "新增行程日"} footer={<><Button variant="secondary" onClick={onClose}>取消</Button><Button type="submit" form="day-form" loading={saving}>儲存</Button></>}><form id="day-form" className="grid-form" onSubmit={submit}><Field label="第幾天"><input className="input" type="number" min="1" name="dayNumber" defaultValue={item?.dayNumber ?? 1} required /></Field><Field label="日期"><input className="input" type="date" name="date" defaultValue={item?.date} required /></Field><Field label="所在城市"><select className="select" name="cityId" defaultValue={item?.cityId} required><option value="">請選擇</option>{cities.map((city) => <option key={city.id} value={city.id}>{city.name}</option>)}</select></Field><Field label="標題"><input className="input" name="title" defaultValue={item?.title} required /></Field><Field label="副標題" className="span-2"><input className="input" name="subtitle" defaultValue={item?.subtitle} /></Field><Field label="備註" className="span-2"><textarea className="textarea" name="note" defaultValue={item?.note} /></Field></form></Dialog>;
}

export function PlaceEditor({ open, item, onClose, onSave }: BaseEditorProps<Place>) {
  const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); const form = new FormData(event.currentTarget); try { await onSave({ id: item?.id ?? createId("place"), name: field(form,"name"), englishName: optional(field(form,"englishName")), time: optional(field(form,"time")), type: field(form,"type") as Place["type"], mapQuery: optional(field(form,"mapQuery")), address: optional(field(form,"address")), note: optional(field(form,"note")), ticketId: optional(field(form,"ticketId")), sortOrder: item?.sortOrder, createdAt: item?.createdAt, updatedAt: item?.updatedAt, updatedBy: item?.updatedBy }); toast.success(item ? "景點已更新" : "景點已新增"); onClose(); } catch (error) { toast.error(error instanceof Error ? error.message : "儲存失敗"); } finally { setSaving(false); } };
  return <Dialog open={open} onClose={onClose} title={item ? "編輯景點" : "新增景點"} footer={<><Button variant="secondary" onClick={onClose}>取消</Button><Button type="submit" form="place-form" loading={saving}>儲存</Button></>}><form id="place-form" className="grid-form" onSubmit={submit}><Field label="名稱"><input className="input" name="name" defaultValue={item?.name} required /></Field><Field label="英文名稱"><input className="input" name="englishName" defaultValue={item?.englishName} /></Field><Field label="時間"><input className="input" type="time" name="time" defaultValue={item?.time} /></Field><Field label="類型"><select className="select" name="type" defaultValue={item?.type ?? "sight"}><option value="sight">景點</option><option value="food">餐飲</option><option value="shopping">購物</option><option value="hotel">住宿</option><option value="transport">交通</option><option value="viewpoint">觀景</option><option value="activity">活動</option><option value="other">其他</option></select></Field><Field label="Google Maps 搜尋字串" className="span-2"><input className="input" name="mapQuery" defaultValue={item?.mapQuery} /></Field><Field label="地址" className="span-2"><input className="input" name="address" defaultValue={item?.address} /></Field><Field label="票券 ID"><input className="input" name="ticketId" defaultValue={item?.ticketId} /></Field><Field label="備註" className="span-2"><textarea className="textarea" name="note" defaultValue={item?.note} /></Field></form></Dialog>;
}

export function TransportEditor({ open, item, onClose, onSave }: BaseEditorProps<DayTransport>) {
  const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); const form = new FormData(event.currentTarget); try { await onSave({ id: item?.id ?? createId("transport"), label: field(form,"label"), type: field(form,"type") as TransportType, from: optional(field(form,"from")), to: optional(field(form,"to")), departureTime: optional(field(form,"departureTime")), arrivalTime: optional(field(form,"arrivalTime")), bookingId: optional(field(form,"bookingId")), note: optional(field(form,"note")), sortOrder: item?.sortOrder, createdAt: item?.createdAt, updatedAt: item?.updatedAt, updatedBy: item?.updatedBy }); toast.success(item ? "交通已更新" : "交通已新增"); onClose(); } catch (error) { toast.error(error instanceof Error ? error.message : "儲存失敗"); } finally { setSaving(false); } };
  return <Dialog open={open} onClose={onClose} title={item ? "編輯當日交通" : "新增當日交通"} footer={<><Button variant="secondary" onClick={onClose}>取消</Button><Button type="submit" form="transport-form" loading={saving}>儲存</Button></>}><form id="transport-form" className="grid-form" onSubmit={submit}><Field label="交通名稱" className="span-2"><input className="input" name="label" defaultValue={item?.label} required /></Field><Field label="類型"><select className="select" name="type" defaultValue={item?.type ?? "local_transport"}><option value="flight">航班</option><option value="train">火車</option><option value="bus">巴士</option><option value="shuttle">接駁</option><option value="rental_car">租車</option><option value="local_transport">市區交通</option></select></Field><Field label="預訂 ID"><input className="input" name="bookingId" defaultValue={item?.bookingId} /></Field><Field label="起點"><input className="input" name="from" defaultValue={item?.from} /></Field><Field label="終點"><input className="input" name="to" defaultValue={item?.to} /></Field><Field label="出發時間"><input className="input" type="time" name="departureTime" defaultValue={item?.departureTime} /></Field><Field label="抵達時間"><input className="input" type="time" name="arrivalTime" defaultValue={item?.arrivalTime} /></Field><Field label="備註" className="span-2"><textarea className="textarea" name="note" defaultValue={item?.note} /></Field></form></Dialog>;
}

function Field({ label, className, children }: { label: string; className?: string; children: React.ReactNode }) { return <label className={className}><span className="field-label">{label}</span>{children}</label>; }
