"use client";

import { useState, type FormEvent } from "react";
import { toast } from "sonner";
import type { Todo } from "@/types/types";
import { createId } from "@/lib/utils";
import { Button } from "./ui/button";
import { Dialog } from "./ui/dialog";

export function TodoEditor({ open, item, onClose, onSave }: { open: boolean; item?: Todo | null; onClose: () => void; onSave: (item: Todo) => Promise<void> }) {
  const [saving,setSaving] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); const form = new FormData(event.currentTarget); const get = (name:string) => String(form.get(name) ?? "").trim(); try { await onSave({ id:item?.id ?? createId("todo"), title:get("title"), category:get("category") as Todo["category"], priority:get("priority") as Todo["priority"], status:get("status") as Todo["status"], city:get("city") || undefined, tripDate:get("tripDate") || undefined, recommendedCompleteDate:get("recommendedCompleteDate") || undefined, nextAction:get("nextAction") || undefined, platform:get("platform") || undefined, bookingNumber:get("bookingNumber") || undefined, note:get("note") || undefined, sortOrder:item?.sortOrder, createdAt:item?.createdAt, updatedAt:item?.updatedAt, updatedBy:item?.updatedBy }); toast.success(item ? "待辦已更新" : "待辦已新增"); onClose(); } catch(error) { toast.error(error instanceof Error ? error.message : "儲存失敗"); } finally { setSaving(false); } };
  return <Dialog open={open} onClose={onClose} title={item ? "編輯待辦" : "新增待辦"} footer={<><Button variant="secondary" onClick={onClose}>取消</Button><Button form="todo-form" type="submit" loading={saving}>儲存</Button></>}><form id="todo-form" className="grid-form" onSubmit={submit}><Field label="待辦事項" className="span-2"><input className="input" name="title" defaultValue={item?.title} required /></Field><Field label="分類"><select className="select" name="category" defaultValue={item?.category ?? "other"}><option value="accommodation">住宿</option><option value="transport">交通</option><option value="ticket">票券</option><option value="other">其他</option></select></Field><Field label="優先度"><select className="select" name="priority" defaultValue={item?.priority ?? "medium"}><option value="high">高</option><option value="medium">中</option><option value="low">低</option></select></Field><Field label="狀態"><select className="select" name="status" defaultValue={item?.status ?? "not_started"}><option value="not_started">未開始</option><option value="in_progress">進行中</option><option value="completed">已完成</option><option value="not_applicable">不適用</option></select></Field><Field label="城市"><input className="input" name="city" defaultValue={item?.city} /></Field><Field label="建議完成日期"><input className="input" type="date" name="recommendedCompleteDate" defaultValue={item?.recommendedCompleteDate} /></Field><Field label="旅程日期"><input className="input" name="tripDate" defaultValue={item?.tripDate} placeholder="2027-03-27 或日期範圍" /></Field><Field label="下一步" className="span-2"><textarea className="textarea" name="nextAction" defaultValue={item?.nextAction} /></Field><Field label="平台"><input className="input" name="platform" defaultValue={item?.platform} /></Field><Field label="訂位代碼"><input className="input" name="bookingNumber" defaultValue={item?.bookingNumber} /></Field><Field label="備註" className="span-2"><textarea className="textarea" name="note" defaultValue={item?.note} /></Field></form></Dialog>;
}

function Field({label,className,children}:{label:string;className?:string;children:React.ReactNode}) { return <label className={className}><span className="field-label">{label}</span>{children}</label>; }
